@host=http://localhost:3000


###
# get all players.
GET {{host}}/v1/players

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 654
etag: W/"28e-ErhO7J/BJAf8Wm2a1D8rmlpeZ5o"
date: Sun, 07 Aug 2022 10:52:14 GMT
connection: close


###
# get a single player by uuid.
GET {{host}}/v1/players/069a79f4-44e9-4726-a5be-fca90e38aaf5

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 209
etag: W/"d1-26hythqToxe8fhdb9lN8Ius5iK4"
date: Sun, 07 Aug 2022 10:52:14 GMT
connection: close


###
# Insert new player
POST {{host}}/v1/players
Content-Type: application/json
{
    "uuid": "69e09d25-0584-445c-ac43-d66a110d1795",
    "username": "Wingoerless"
}

HTTP/1.1 409  - Conflict
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 25
etag: W/"19-OqrwLljcLBdgxRAEjhlo5YCBVZ8"
date: Sun, 07 Aug 2022 10:52:14 GMT
connection: close


###
# complete the link process.
POST {{host}}/v1/link/YOa6muEF
Content-Type: application/json
{
    "name": "jojo the awesome",
    "guilded_username" : null,
    "email": "tom.parker1235@gmail.com"
}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 0
etag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
date: Sun, 07 Aug 2022 10:52:17 GMT
connection: close


###
# Email verifcation
GET {{host}}/v1/link/YOa6muEF/Cgrsbau1HEyIIVQg9jtI8OpZbzY2NYs5

HTTP/1.1 404  - Not Found
x-powered-by: Express
date: Sun, 07 Aug 2022 10:58:17 GMT
connection: close
content-length: 0