@host=http://localhost:{{HTTP_PORT}}


###
# get all players.
GET {{host}}/v1/players
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 641
etag: W/"281-azF5PMuJVD2z5oj6bwTgSuBeYp8"
date: Mon, 08 Aug 2022 06:03:39 GMT
connection: close


###
# get a single player by uuid.
GET {{host}}/v1/players/069a79f4-44e9-4726-a5be-fca90e38aaf5
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 209
etag: W/"d1-26hythqToxe8fhdb9lN8Ius5iK4"
date: Mon, 08 Aug 2022 06:03:38 GMT
connection: close


###
# Insert new player
POST {{host}}/v1/players
Authorization: {{API_KEY}}
Content-Type: application/json
{
    "uuid": "69e09d25-0584-445c-ac43-d66a110d1795",
    "username": "Wingoerless"
}


HTTP/1.1 409  - Conflict
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 25
etag: W/"19-OqrwLljcLBdgxRAEjhlo5YCBVZ8"
date: Mon, 08 Aug 2022 06:03:52 GMT
connection: close


###
# complete the link process.
POST {{host}}/v1/link/b3qa4OIS
Content-Type: application/json
{
    "name": "Gabe Newel",
    "guilded_username" : null,
    "email": "tom.parker1235@gmail.com"
}


HTTP/1.1 201  - Created
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 0
etag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
date: Mon, 08 Aug 2022 05:10:31 GMT
connection: close


###
# Email verifcation
GET {{host}}/v1/link/b3qa4OIS/A7QHFVWrShyouc0Y9SZQR3yT5XR8lJEK

HTTP/1.1 200  - OK
x-powered-by: Express
date: Mon, 08 Aug 2022 05:14:17 GMT
connection: close
content-length: 0