@host=http://localhost:{{HTTP_PORT}}


###
# get all players.
GET {{host}}/v1/players
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 635
etag: W/"27b-41gJesQ0Zp7CyR1OqTDd2jATQpA"
date: Mon, 08 Aug 2022 08:13:05 GMT
connection: close


###
# get a single player by uuid.
GET {{host}}/v1/players/069a79f4-44e9-4726-a5be-fca90e38aaf5
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 204
etag: W/"cc-ffEolBQ8/KQErVrZ7iZ6zUi6r48"
date: Mon, 08 Aug 2022 08:13:03 GMT
connection: close


###
# Insert new player
POST {{host}}/v1/players
Authorization: {{API_KEY}}
Content-Type: application/json
{
    "uuid": "69e09d25-0584-445c-ac43-d66a110d1795",
    "username": "Wingoerless"
}



HTTP/1.1 409  - Conflict
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 25
etag: W/"19-OqrwLljcLBdgxRAEjhlo5YCBVZ8"
date: Mon, 08 Aug 2022 06:26:27 GMT
connection: close


###
# get details from link.
GET {{host}}/v1/link/expired

HTTP/1.1 410  - Gone
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 17
etag: W/"11-sQFWVkXGnmZTHVQfXI9qH32O0RA"
date: Mon, 08 Aug 2022 08:52:02 GMT
connection: close


###
# complete the link process.
POST {{host}}/v1/link/expired
Content-Type: application/json
{
    "name": "Bing Bong",
    "guilded_username" : null,
    "email": "tom.parker1235@gmail.com"
}



HTTP/1.1 410  - Gone
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 17
etag: W/"11-sQFWVkXGnmZTHVQfXI9qH32O0RA"
date: Mon, 08 Aug 2022 08:27:08 GMT
connection: close


###
# Email verifcation
GET {{host}}/v1/link/b3qa4OIS/A7QHFVWrShyouc0Y9SZQR3yT5XR8lJEK

HTTP/1.1 404  - Not Found
x-powered-by: Express
date: Mon, 08 Aug 2022 08:27:12 GMT
connection: close
content-length: 0