@host=http://localhost:{{HTTP_PORT}}


###
# get all players.
GET {{host}}/v1/players
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 650
etag: W/"28a-SQpSq6fsQB3fn7HqP1S1qZRuyfU"
date: Mon, 08 Aug 2022 11:16:55 GMT
connection: close


###
# get a single player by uuid.
GET {{host}}/v1/players/7c529ba2-162f-11ed-861d-0242ac120002
Authorization: {{API_KEY}}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 320
etag: W/"140-k6OGeH+bwQCDQ598X4ONx8gRZ4k"
date: Mon, 08 Aug 2022 11:22:48 GMT
connection: close


###
# Insert new player
POST {{host}}/v1/players
Authorization: {{API_KEY}}
Content-Type: application/json
{
    "uuid": "69e09d25-0584-445c-ac43-d66a110d1795",
    "username": "Wingoerless"
}



HTTP/1.1 409  - Conflict
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 25
etag: W/"19-OqrwLljcLBdgxRAEjhlo5YCBVZ8"
date: Mon, 08 Aug 2022 10:46:37 GMT
connection: close


###
# Create a new link for a player
GET {{host}}/v1/players/7c529ba2-162f-11ed-861d-0242ac120002/new-link
Authorization: {{API_KEY}}

HTTP/1.1 201  - Created
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 138
etag: W/"8a-KiV+9PAX6qgD+Y4Jl9JdEWzRgwQ"
date: Mon, 08 Aug 2022 11:33:33 GMT
connection: close


###
# get details from link.
GET {{host}}/v1/link/expired

HTTP/1.1 410  - Gone
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 17
etag: W/"11-sQFWVkXGnmZTHVQfXI9qH32O0RA"
date: Mon, 08 Aug 2022 08:52:02 GMT
connection: close


###
# complete the link process.
POST {{host}}/v1/link/expired
Content-Type: application/json
{
    "name": "Bing Bong",
    "guilded_username" : null,
    "email": "tom.parker1235@gmail.com"
}



HTTP/1.1 410  - Gone
x-powered-by: Express
content-type: text/html; charset=utf-8
content-length: 17
etag: W/"11-sQFWVkXGnmZTHVQfXI9qH32O0RA"
date: Mon, 08 Aug 2022 08:27:08 GMT
connection: close


###
# Email verifcation
GET {{host}}/v1/link/b3qa4OIS/A7QHFVWrShyouc0Y9SZQR3yT5XR8lJEK

HTTP/1.1 404  - Not Found
x-powered-by: Express
date: Mon, 08 Aug 2022 08:27:12 GMT
connection: close
content-length: 0